version: "3"
services: 
  reverseproxy:
    build: 
      context: . 
    image: zubair/udacity-reverse-proxy
  backend_user:
    build: 
      context: ../../udacity-c3-restapi-user
    image: zubair/udacity-rest-api-user    
  backend_feed:
    build: 
      context: ../../udacity-c3-restapi-feed
    image: zubair/udacity-rest-api-feed
  frontend:
    build: 
      context: ../../udacity-c3-frontend
    image: zubair/udacity-frontend:local