apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - image: zubairriaz78696/udacity-frontend
        name: frontend
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
      restartPolicy: Always
           